services:
  mysql:
    image: mysql:8.0
    container_name: backend_tarifas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_tarifas
      MYSQL_USER: backend_user
      MYSQL_PASSWORD: backend_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
